export const ADD_ARTICLE = 'ADD_ARTICLE';
export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';
export const DATA_LOADED = 'DATA_LOADED';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const OPEN_MODAL_REGISTER = 'OPEN_MODAL_REGISTER';
export const CLOSE_MODAL_REGISTER = 'CLOSE_MODAL_REGISTER';
export const OPEN_MODAL_LOGIN = 'OPEN_MODAL_LOGIN';
export const CLOSE_MODAL_LOGIN = 'CLOSE_MODAL_LOGIN';

export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCSESS = 'GET_MOVIES_SUCCSESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const GET_TV_REQUEST = 'GET_TV_REQUEST';
export const GET_TV_SUCCSESS = 'GET_TV_SUCCSESS';
export const GET_TV_ERROR = 'GET_TV_ERROR';

export const GET_DETAIL_MOVIE_REQUEST = 'GET_DETAIL_MOVIE_REQUEST';
export const GET_DETAIL_MOVIE_SUCCSESS = 'GET_DETAIL_MOVIE_SUCCSESS';
export const GET_DETAIL_MOVIE_ERROR = 'GET_DETAIL_MOVIE_ERROR';
